export const permissionOptions = {
  Dashboard: [{ label: "view", value: "view" }],
  featured_category_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "enable", value: "enable" },
  ],
  domain_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "enable", value: "enable" },
  ],
  referral_and_gifts: [
    { label: "view", value: "view" },
    { label: "update", value: "update" },
    { label: "enable", value: "enable" },
  ],
  admin_user_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "enable", value: "enable" },
  ],
  roles_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "enable", value: "enable" },
  ],
  course_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "publish_course", value: "publish_course" },
    { label: "curriculum", value: "curriculum" },
    { label: "rating", value: "rating" },
    { label: "annoucements", value: "annoucements" },
    { label: "resources", value: "resources" },
    { label: "course_assessment", value: "course_assessment" },
  ],
  application_user_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "enable", value: "enable" },
  ],
  insight_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
  ],
  banners_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
  ],
  subscription_management: [
    { label: "add", value: "add" },
    { label: "update", value: "update" },
    { label: "delete", value: "delete" },
    { label: "view", value: "view" },
    { label: "publish", value: "publish" },
  ],
  payment_management: [
    { label: "view", value: "view" },
    { label: "view_refund", value: "view_refund" },
    { label: "initiate_refund", value: "initiate_refund" },
  ],
  static_content_management: [
    { label: "view", value: "view" },
    { label: "privacy_policy", value: "privacy_policy" },
    { label: "terms & condition", value: "terms_and_condition" },
    { label: "faq", value: "faq" },
    { label: "publish", value: "publish" },
    { label: "unpublish", value: "unpublish" },
  ],
};
